from stable_baselines3 import PPO
from air_hockey_env import AirHockeyEnv

env = AirHockeyEnv()
obs, _ = env.reset()

# file path generated by train.py
model_path = "models/PPO/500000.zip"

try:
    model = PPO.load(model_path, env=env)
    print(f"Załadowano model: {model_path}")
except FileNotFoundError:
    print("Błąd: Nie znaleziono pliku modelu! Uruchom najpierw train.py.")
    exit()

print("Rozpoczynam grę testową...")

while True:
    # deterministic=True => plays at his best, no randomness
    action, _ = model.predict(obs, deterministic=True)

    obs, reward, terminated, truncated, info = env.step(action)

    env.render()

    if terminated or truncated:
        obs, _ = env.reset()
